stages:
  - test

run_ui_tests:
  stage: test
  image: maven:3.9.6
  before_script:
    - apt-get update
    - apt-get install -y wget gnupg2 unzip
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    - apt-get update
    - apt-get install -y google-chrome-stable
  script:
    - mvn clean test -Denv=qa -Dheadless=true
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
      - target/